#! /usr/bin/env python3
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Copyright © 2021 Albert Lv <altair.albert@yahoo.com>
#
# Distributed under terms of the MIT license.
"""

"""

import os
import subprocess
import shutil
import argparse

__VERSION__ = '0.0.1'
XDG_CONFIG_PATH = os.environ.get('XDG_CONFIG_PATH')
HOME = str(os.environ.get("HOME"))

if XDG_CONFIG_PATH is None or XDG_CONFIG_PATH == "":
    XDG_CONFIG_PATH = HOME + "/.config"

DOTFILE_DIR = XDG_CONFIG_PATH + '/' + 'dotfile'


def git_exist():
    completed = subprocess.run(['git', '--version'], capture_output=True)
    return completed.returncode == 0


def is_repo():
    return os.path.exists(DOTFILE_DIR)


def diff(args):
    if is_repo():
        os.chdir(DOTFILE_DIR)
        subprocess.run(['git', 'diff'])


def status(args):
    if is_repo():
        os.chdir(DOTFILE_DIR)
        ouput = subprocess.run(['git', 'status', '-s'], capture_output=True)
        if ouput.stdout is None:
            print("Everything is update!")
        else:
            print(ouput.stdout.decode('utf-8'))
    else:
        print("Error, not a repo, init or sync from remote first")


def abandon(args):
    if is_repo():
        os.chdir(DOTFILE_DIR)
        subprocess.run(['git', 'checkout', '.'])
    else:
        print("Error, not a repo, init or sync from remote first")


def add(args):
    if is_repo():
        for file in args.files:
            file = os.path.abspath(file)
            if os.path.isfile(file):
                dir_name = os.path.dirname(file)
                file_name = os.path.basename(file)
                if str(dir_name).startswith(HOME):
                    dir_name = dir_name.replace(HOME, '.')
                dst_dir = DOTFILE_DIR + '/' + dir_name
                if os.path.exists(dst_dir + '/' + file_name):
                    print("Error, File exists.")
                    return False
                os.makedirs(dst_dir, 0o755, exist_ok=True)
                return shutil.copy(file, dst_dir, follow_symlinks=False)
            else:
                print("Error, Need one file")
    else:
        print("Error, not a repo")


def sync(args):
    remote = args.url
    if not os.path.exists(DOTFILE_DIR):
        os.makedirs(DOTFILE_DIR, 0o755)
    os.chdir(DOTFILE_DIR)
    if not remote is None:
        subprocess.run(['git', 'clone', remote, '.'])
    else:
        subprocess.run(['git', 'pull'])


def upload(args):
    if is_repo():
        os.chdir(DOTFILE_DIR)
        completed = subprocess.run(['git', 'status', '-s'],
                                   encoding='utf-8',
                                   capture_output=True)
        if completed.returncode == 0:
            if not completed.stdout is None:
                lines = completed.stdout.splitlines(False)
                files = [line.split(' ')[-1] for line in lines]
                if len(files) > 0:
                    subprocess.run(['git', 'add', '.'])
                    subprocess.run([
                        'git', 'commit', '-m',
                        ','.join(map(lambda x: os.path.basename(x), files))
                    ])
                else:
                    return
            else:
                print("No File change.")
                return

        if subprocess.run(['git', 'remote', 'show', 'origin'],
                          capture_output=True).returncode == 0:
            subprocess.run(['git', 'push'])


def remove(file):
    if is_repo():
        if not unlink(file):
            return False
        file = os.path.abspath(file)
        dir_name = os.path.dirname(file)
        file_name = os.path.basename(file)
        if str(dir_name).startswith(HOME):
            dir_name = dir_name.replace(HOME, '.')

        dst_dir = DOTFILE_DIR + '/' + dir_name
        if os.path.exists(dst_dir + '/' + file_name):
            return subprocess.run(
                ['git', 'rm', dst_dir + '/' + file_name, '-f']).returncode == 0
        else:
            print("Error, No file find.")
            return False


def link(args):
    file = args.options[0]
    if is_repo():
        dir_name = os.path.dirname(file)
        file_name = os.path.basename(file)
        if str(dir_name).startswith(HOME):
            dir_name = dir_name.replace(HOME, '.')

        dst_dir = DOTFILE_DIR + '/' + dir_name
        store_file = os.path.abspath(dst_dir + '/' + file_name)
        if os.path.exists(store_file):
            if os.path.exists(file):
                overwrite = input("File is exists, Overwrite(Y/n)? ")
                if overwrite == 'Y' or overwrite == 'y':
                    os.remove(file)
                else:
                    print("Cancel by user!")
                    return False
            os.symlink(store_file, file)
            return True
        else:
            print("Error, No file find, use add command first.")
            return False


def unlink(args):
    file = args.options[0]
    if is_repo():
        file = os.path.abspath(file)
        if os.path.islink(file):
            dir_name = os.path.dirname(file)
            file_name = os.path.basename(file)
            if str(dir_name).startswith(HOME):
                dir_name = dir_name.replace(HOME, '.')
            dst_dir = DOTFILE_DIR + '/' + dir_name
            if os.path.exists(dst_dir + '/' + file_name):
                os.unlink(file)
                shutil.copy(dst_dir + '/' + file_name, file)
                return True
            else:
                print("Error, No file find, use add command first.")
                return False
        else:
            print("Error, Need one file without link.")


def get_paser():
    parser = argparse.ArgumentParser()
    sub_parser = parser.add_subparsers(
        title='dotfile command', help='command help')
    status_parser = sub_parser.add_parser('status', help='dotfile repo status')
    status_parser.add_argument('-q', help='small message')
    status_parser.set_defaults(func=status)

    abandon_paser = sub_parser.add_parser(
        'abandon', help='abandon local change')
    abandon_paser.set_defaults(func=abandon)

    diff_paser = sub_parser.add_parser('diff', help='change of repo')
    diff_paser.set_defaults(func=diff)

    upload_paser = sub_parser.add_parser(
        'upload', help='upload repo to server')
    upload_paser.set_defaults(func=upload)

    remove_paser = sub_parser.add_parser('remove', help='remove from repo')
    remove_paser.add_argument('options', nargs="*")
    remove_paser.set_defaults(func=remove)

    add_paser = sub_parser.add_parser('add', help='add file to repo')
    add_paser.add_argument('files', nargs="*")
    add_paser.set_defaults(func=add)

    sync_paser = sub_parser.add_parser('sync', help='sync repo from server')
    sync_paser.add_argument('url', nargs='?', type=str, default=None)
    sync_paser.set_defaults(func=sync)

    link_paser = sub_parser.add_parser('link', help='link file')
    link_paser.add_argument('options', nargs=1)
    link_paser.set_defaults(func=link)

    unlink_paser = sub_parser.add_parser('unlink', help='unlink file')
    unlink_paser.add_argument('options', nargs="*")
    unlink_paser.set_defaults(func=unlink)

    parser.add_argument('-v',
                        '--version',
                        action='version',
                        version=__VERSION__,
                        help='show version')

    return parser


if __name__ == '__main__':
    parser = get_paser()
    if not git_exist():
        print("Need install git first")
    else:
        args = parser.parse_args()
        if 'func' in args:
            args.func(args)
        else:
            parser.print_help()
